id: P76757722
initial_creation_type: input
source_metadata:
  title: Buddha Śākyamuni
  language: it
  description: 'Texts by and about Buddha Śākyamuni (shākya thub pa):'
  volume:
    6d8b3c3f6b8745fda24073f447670fb8:
      title: Guru Yoga of the Guru Mahāmuni
      parent: Guru Yoga
    1eb2eae7738749bd8f84556689bc19e3:
      title: 'The Merry Sea of Blessings: A Guru Yoga of the Lord of Sages, Peerless
        Teacher of All, Including the Devas'
      parent: Guru Yoga
    817ba87a37b14792afa7d0d5e541783f:
      title: In Praise of the Twelve Deeds of the Buddha
      parent: Praise
    f6808046b3b94bb3b25e950031bae5be:
      title: 'Praise of the Buddha: With Skilful Means & Compassion...'
      parent: Praise
    f05645df2b224eabb452c7f2dd3e0e5c:
      title: Praise of the Twelve Acts of the Buddha
      parent: Praise
    e12332b536fd4b608db2a463774c54b3:
      title: Short Praise of the Buddha's Deeds
      parent: Praise
    934273c0187540f48f8215d1bf8a5092:
      title: Supplication to Lord Buddha together with the Sixteen Arhats
      parent: Prayers
    41f2052f4dc549d2b3004eed19038d93:
      title: Verses on the Buddha's Previous Lives
      parent: Prayers
    b7b86ab983c34dc4b2a54fbe018387d5:
      title: 'The Treasury of Blessings: A Practice of Buddha Śākyamuni'
      parent: Prayers to Śākyamuni
created_at: '2022-03-01T02:12:34.857497'
last_modified_at: '2022-03-01T02:12:34.857499'
